name: Create and Upload Release ZIP

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Adjust the PHP version as needed

      - name: Create ZIP File
        id: create_zip
        run: |
          THEME_NAME="celestialinterface"
          VERSION="${GITHUB_REF#refs/tags/}"
          ZIP_NAME="${THEME_NAME}-${VERSION}.zip"

          # Remove any existing ZIP to avoid conflicts
          rm -f ${ZIP_NAME}

          # Create the ZIP without nesting
          zip -r ${ZIP_NAME} . -x "*.git*" "*.github*" "README.md" "LICENSE" "node_modules/*" "*.DS_Store" "*.zip"

          # Ensure the ZIP was created
          if [ ! -f "${ZIP_NAME}" ]; then
            echo "ZIP creation failed."
            exit 1
          fi

          # Set the ZIP_NAME as an output
          echo "zip_name=${ZIP_NAME}" >> $GITHUB_OUTPUT

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.create_zip.outputs.zip_name }}
          asset_name: ${{ steps.create_zip.outputs.zip_name }}
          asset_content_type: application/zip
